export const enumParametrosPowwi = Object.freeze({
    MIN_DEPOSITO_SERVICIOS_POWWI: 1000,
    MAX_DEPOSITO_SERVICIOS_POWWI: 1000000,
    MIN_RETIRO_SERVICIOS_POWWI: 1000,
    MAX_RETIRO_SERVICIOS_POWWI: 1000000,
  });

