export const enumParametrosCajaSocial = Object.freeze({
  MIN_DEPOSITO_CAJA_SOCIAL: 1000,
  MAX_DEPOSITO_CAJA_SOCIAL: 1300000,

  MIN_PAGO_PRODUCTOS_PROPIOS_CAJA_SOCIAL: 1000,
  MAX_PAGO_PRODUCTOS_PROPIOS_CAJA_SOCIAL: 1300000,
});
