export const enumParametrosNequi = Object.freeze({
  MAX_RETIRO_NEQUI_NOTIFICACION: 500000,
  MIN_RETIRO_NEQUI_NOTIFICACION: 10000,
  COSTO_TRANSACCION_RETIRO_NEQUI_NOTIFICACION: 1500,
  PORCENTAJE_IMPUESTO_RETIRO_NEQUI_NOTIFICACION: 0,
  MAX_RECARGA_CUPO_NEQUI_NOTIFICACION: 9900000,
  MIN_RECARGA_CUPO_NEQUI_NOTIFICACION: 10000,
  COSTO_TRANSACCION_RECARGA_CUPO_NEQUI_NOTIFICACION: 1500,
  PORCENTAJE_IMPUESTO_RECARGA_CUPO_NEQUI_NOTIFICACION: 0,
});
