# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "certificacion" ]
  # pull_request:
  #   branches: [ "certificacion" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
  # applicationfolder: spring-boot-hello-world-example
  # S3BUCKET: buc

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      id-token: write
    
    env:
      env: cert

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role-deploy
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      

      - name: chmod github folder
        run: chmod -R +x ./.github

      - name: Get env variables
        run: $GITHUB_WORKSPACE/.github/scripts/get-env-vars.sh $GITHUB_REPOSITORY ${{ env.ENV_NAME }}
      
      - name: Install dependencies 🔨
        run: yarn

      - name: Build 📦
        run: yarn build
        
      - name: Deploy 🚀
        run: |
          aws s3 sync build s3://${{ secrets.S3_BUCKET_DEV }}
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
